project:
  type: website
  output-dir: docs

website:
  title: "Cancer Rates By Geographic Area"
  search: false
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd 
        text: Home
      - href: abstract.qmd 
        text: Abstract
      - href: background.qmd 
        text: Background Information
      - href: purpose.qmd 
        text: Aim of Research
      - href: methods.qmd
        text: Methods
      - href: results.qmd 
        text: Results
      - href: conclusion.qmd 
        text: Conclusion

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    code-fold: true