# Conclusion

We found that there is a significant difference in the rates of lung cancer mortality between different geographic areas of Multnomah County. Specifically, there was a trend of higher rates in Eastern areas and lower rates in Northern areas. To add context to this trend it is important to note that Northwest Portland has undergone rapid gentrification and is now very affluent whereas East Portland is home to more underserved communities who face inequities and barriers as a consequence. This suggests that the disparity in lung cancer deaths may be influenced by social determinants of health more than physical environmental hazards.

Looking at research on the association between lung cancer and demographic factors such as income, education, race, gender, and smoking habits in conjunction with census population data can further illuminate the spatial distribution of mortality rates. Our study did not find significant differences in the rates of breast or pancreatic cancer mortality among different geographic areas. Future research may uncover different results by addressing and correcting some of the limitations of this study such as missing geographic data and lack of gender distinction in breast cancer rate calculation.
